### ISSUE TITLE
Change color of search input boxes to grey

### ISSUE THREAD

**Issue by zross** [WHOequity/who-heat#233]
•	Please return back the grey color text within the search cell at the bottom of each column in the Explore inequality/disaggregated & summary measures tables.

**Comment by zross** [comment]
```css
div.dataTables_scrollFoot table input[type="text"]{
    background-color: #dddddd;
}
```
