### ISSUE TITLE
Design: lighter Shiny style

### ISSUE THREAD

**Issue by zross** [WHOequity/who-heat#3]
Shiny style should be changed to something lighter (e.g. cerulean)

**Comment by WHOequity** [comment]
Can we change the style of the left panel back to its previous version? We preferred the lighter version.

**Comment by WHOequity** [comment]
![untitled](https://cloud.githubusercontent.com/assets/13563065/10582453/3bc2a058-7688-11e5-9773-16f919c31908.png)

**Comment by zross** [comment]
This is part of the alternate shiny style but I changed back to the original grey:
background-color: #F7F7F7;
border: 1px solid #E5E5E5;

**Comment by WHOequity** [comment]
Great! Can we also get rid of the white space between the side panel and the main window?

**Comment by zross** [comment]
I got rid of much of the white space but getting rid of all does not look good. Here are the specs:

```css
.col-sm-4 {
    width: 35%;
    padding-right:5px;
}

.col-sm-8 {
    width: 65%;
    padding-left:5px;
}

```
